name: Python Tests

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Change this to your desired Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install docker compose 
      run: |
        sudo apt-get update 
        sudo apt-get install -y docker-compose

    - name: Up docker compose
      run: sudo docker-compose up -d
      working-directory: ./docker

    - name: Run tests
      run: |
        pytest